/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Sheena
 */
public class GameFile extends javax.swing.JFrame {

    /**
     * Creates new form GameFile
     */
    public GameFile() {
        initComponents();
        
        String[] comboBoxOptions = new String[Globals.currentComboBoxOptions.size()];
        for (int i = 0; i < Globals.currentComboBoxOptions.size(); i++) {
            comboBoxOptions[i] = Globals.currentComboBoxOptions.get(i);
        }
        taskJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxOptions));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        levelNumJLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numOfFavourPointsJLabel = new javax.swing.JLabel();
        inventoryJPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        notesJPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        descriptionJTextArea = new javax.swing.JTextArea();
        optionAJPanel = new javax.swing.JPanel();
        optionAJTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        taskJComboBox = new javax.swing.JComboBox<>();
        confirmJButton = new javax.swing.JButton();
        optionCJPanel = new javax.swing.JPanel();
        optionCJTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        optionDJPanel = new javax.swing.JPanel();
        optionDJTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        optionBJPanel = new javax.swing.JPanel();
        optionBJTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        exitGameJButton = new javax.swing.JButton();
        buyJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        exitGameJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(86, 105, 191));

        levelNumJLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 36)); // NOI18N
        levelNumJLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelNumJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelNumJLabel.setText("LEVEL 1: EARTH");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(47, 65, 151));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(levelNumJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(levelNumJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Number of NASA");

        jLabel6.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Favour Points:");

        numOfFavourPointsJLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        numOfFavourPointsJLabel.setForeground(new java.awt.Color(0, 0, 0));
        numOfFavourPointsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numOfFavourPointsJLabel.setText("5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numOfFavourPointsJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numOfFavourPointsJLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        inventoryJPanel.setBackground(new java.awt.Color(224, 228, 252));
        inventoryJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryJPanelMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INVENTORY");

        javax.swing.GroupLayout inventoryJPanelLayout = new javax.swing.GroupLayout(inventoryJPanel);
        inventoryJPanel.setLayout(inventoryJPanelLayout);
        inventoryJPanelLayout.setHorizontalGroup(
            inventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(inventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventoryJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        inventoryJPanelLayout.setVerticalGroup(
            inventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(inventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventoryJPanelLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel8)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        notesJPanel.setBackground(new java.awt.Color(224, 228, 252));
        notesJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesJPanelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NOTES");

        javax.swing.GroupLayout notesJPanelLayout = new javax.swing.GroupLayout(notesJPanel);
        notesJPanel.setLayout(notesJPanelLayout);
        notesJPanelLayout.setHorizontalGroup(
            notesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(notesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(notesJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        notesJPanelLayout.setVerticalGroup(
            notesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(notesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(notesJPanelLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel9)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(242, 242, 242));

        descriptionJTextArea.setEditable(false);
        descriptionJTextArea.setBackground(new java.awt.Color(242, 242, 242));
        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descriptionJTextArea.setRows(5);
        descriptionJTextArea.setText("Hello young scientist! You must do a series of activities before \nyou can successfully visit space. Planning a space mission can \nsometimes take years, and training usually lasts for about 2 \nyears, so be prepared!\n\n");
        descriptionJTextArea.setBorder(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(descriptionJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(descriptionJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        optionAJPanel.setBackground(new java.awt.Color(242, 242, 242));
        optionAJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionAJPanelMouseClicked(evt);
            }
        });

        optionAJTextArea.setEditable(false);
        optionAJTextArea.setBackground(new java.awt.Color(242, 242, 242));
        optionAJTextArea.setColumns(20);
        optionAJTextArea.setRows(5);
        optionAJTextArea.setBorder(null);
        optionAJTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionAJTextAreaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("A)");

        javax.swing.GroupLayout optionAJPanelLayout = new javax.swing.GroupLayout(optionAJPanel);
        optionAJPanel.setLayout(optionAJPanelLayout);
        optionAJPanelLayout.setHorizontalGroup(
            optionAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionAJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionAJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionAJPanelLayout.setVerticalGroup(
            optionAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionAJPanelLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(optionAJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionAJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        jPanel6.setBackground(new java.awt.Color(242, 242, 242));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TASK:");

        taskJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Composition of Atmosphere" }));
        taskJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                taskJComboBoxItemStateChanged(evt);
            }
        });
        taskJComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                taskJComboBoxMousePressed(evt);
            }
        });
        taskJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskJComboBoxActionPerformed(evt);
            }
        });

        confirmJButton.setText("CONFIRM");
        confirmJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskJComboBox, 0, 191, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(confirmJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionCJPanel.setBackground(new java.awt.Color(242, 242, 242));
        optionCJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionCJPanelMouseClicked(evt);
            }
        });

        optionCJTextArea.setEditable(false);
        optionCJTextArea.setBackground(new java.awt.Color(242, 242, 242));
        optionCJTextArea.setColumns(20);
        optionCJTextArea.setRows(5);
        optionCJTextArea.setBorder(null);
        optionCJTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionCJTextAreaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("C)");

        javax.swing.GroupLayout optionCJPanelLayout = new javax.swing.GroupLayout(optionCJPanel);
        optionCJPanel.setLayout(optionCJPanelLayout);
        optionCJPanelLayout.setHorizontalGroup(
            optionCJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionCJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionCJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionCJPanelLayout.setVerticalGroup(
            optionCJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionCJPanelLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(optionCJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionCJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
        );

        optionDJPanel.setBackground(new java.awt.Color(242, 242, 242));
        optionDJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionDJPanelMouseClicked(evt);
            }
        });

        optionDJTextArea.setEditable(false);
        optionDJTextArea.setBackground(new java.awt.Color(242, 242, 242));
        optionDJTextArea.setColumns(20);
        optionDJTextArea.setRows(5);
        optionDJTextArea.setBorder(null);
        optionDJTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionDJTextAreaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("D)");

        javax.swing.GroupLayout optionDJPanelLayout = new javax.swing.GroupLayout(optionDJPanel);
        optionDJPanel.setLayout(optionDJPanelLayout);
        optionDJPanelLayout.setHorizontalGroup(
            optionDJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionDJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionDJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionDJPanelLayout.setVerticalGroup(
            optionDJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionDJPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42))
            .addGroup(optionDJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionDJTextArea)
                .addContainerGap())
        );

        optionBJPanel.setBackground(new java.awt.Color(242, 242, 242));
        optionBJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionBJPanelMouseClicked(evt);
            }
        });

        optionBJTextArea.setEditable(false);
        optionBJTextArea.setBackground(new java.awt.Color(242, 242, 242));
        optionBJTextArea.setColumns(20);
        optionBJTextArea.setRows(5);
        optionBJTextArea.setBorder(null);
        optionBJTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionBJTextAreaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("B)");

        javax.swing.GroupLayout optionBJPanelLayout = new javax.swing.GroupLayout(optionBJPanel);
        optionBJPanel.setLayout(optionBJPanelLayout);
        optionBJPanelLayout.setHorizontalGroup(
            optionBJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionBJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionBJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        optionBJPanelLayout.setVerticalGroup(
            optionBJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionBJPanelLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(optionBJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionBJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(optionAJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optionBJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(optionCJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optionDJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optionBJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionAJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionCJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionDJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        exitGameJButton.setBackground(new java.awt.Color(255, 102, 102));
        exitGameJButton.setForeground(new java.awt.Color(0, 0, 0));
        exitGameJButton.setText("EXIT GAME");
        exitGameJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameJButtonActionPerformed(evt);
            }
        });

        buyJPanel.setBackground(new java.awt.Color(224, 228, 252));
        buyJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyJPanelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BUY");

        javax.swing.GroupLayout buyJPanelLayout = new javax.swing.GroupLayout(buyJPanel);
        buyJPanel.setLayout(buyJPanelLayout);
        buyJPanelLayout.setHorizontalGroup(
            buyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
            .addGroup(buyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buyJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        buyJPanelLayout.setVerticalGroup(
            buyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(buyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buyJPanelLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel11)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        exitGameJButton1.setBackground(new java.awt.Color(168, 178, 221));
        exitGameJButton1.setForeground(new java.awt.Color(0, 0, 0));
        exitGameJButton1.setText("HELP");
        exitGameJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inventoryJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(exitGameJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(notesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buyJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitGameJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inventoryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitGameJButton)
                            .addComponent(exitGameJButton1)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryJPanelMouseClicked
        String[] random = {};
        new Inventory().runInventory(random);
    }//GEN-LAST:event_inventoryJPanelMouseClicked

    private void notesJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesJPanelMouseClicked
        
        String[] random = {};
        new NotesPanel().runNotes(random);
        
    }//GEN-LAST:event_notesJPanelMouseClicked

    private void taskJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskJComboBoxActionPerformed

    private void optionAJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionAJPanelMouseClicked
        
        option("A", 5, 0);
        
    }//GEN-LAST:event_optionAJPanelMouseClicked

    private void taskJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_taskJComboBoxItemStateChanged
        
        
    }//GEN-LAST:event_taskJComboBoxItemStateChanged

    private void buyJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyJPanelMouseClicked
        String[] random = {};
        new Buy2().runBuy(random);
    }//GEN-LAST:event_buyJPanelMouseClicked

    private void exitGameJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitGameJButtonActionPerformed

    private void exitGameJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameJButton1ActionPerformed
        String[] random = {};
        new TitanHelpDesign().runHelp(random);
    }//GEN-LAST:event_exitGameJButton1ActionPerformed

    private void optionBJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionBJPanelMouseClicked
        option("B", 6, 1);
    }//GEN-LAST:event_optionBJPanelMouseClicked

    private void optionAJTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionAJTextAreaMouseClicked
        
        option("A", 5, 0);
    }//GEN-LAST:event_optionAJTextAreaMouseClicked

    private void taskJComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskJComboBoxMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskJComboBoxMousePressed

    private void confirmJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmJButtonActionPerformed
        
        if (confirmJButton.getText().equalsIgnoreCase("Confirm")) {
            
            int k = taskJComboBox.getSelectedIndex();
            Globals.task = Globals.currentComboBoxOptions.get(k);
            

            String[] arr = StaticMethods.findArray();
            int lastSpace = 0;
            String arr1 = arr[1];
            int numOfEnters = 0;
            int j = 0;
            if (arr[1].length() > 45) {
                for (int i = 0; i < arr[1].length(); i++) {
                    if (arr[1].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 45) {
                        arr1 = arr1.substring(0, lastSpace) + "\n" + arr1.substring(lastSpace + 1);
                        j = i - lastSpace;
                        numOfEnters++;
                    }
                    j++;
                }
            }
            for (int q = 0; q < 3 - Math.ceil(numOfEnters / 2.0); q++) {
                arr1 = "\n" + arr1;
            }

            lastSpace = 0;
            String arr2 = arr[2];
            numOfEnters = 0;
            j = 0;
            if (arr[2].length() > 45) {
                for (int i = 0; i < arr[2].length(); i++) {
                    if (arr[2].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 45) {
                        arr2 = arr2.substring(0, lastSpace) + "\n" + arr2.substring(lastSpace + 1);
                        j = i - lastSpace;
                        numOfEnters++;
                    }
                    j++;
                }
            }
            for (int q = 0; q < 3 - Math.ceil(numOfEnters / 2.0); q++) {
                arr2 = "\n" + arr2;
            }

            lastSpace = 0;
            String arr3 = arr[3];
            numOfEnters = 0;
            j = 0;
            if (arr[3].length() > 45) {
                for (int i = 0; i < arr[3].length(); i++) {
                    if (arr[3].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 45) {
                        arr3 = arr3.substring(0, lastSpace) + "\n" + arr3.substring(lastSpace + 1);
                        j = i - lastSpace;
                        numOfEnters++;
                    }
                    j++;
                }
            }
            for (int q = 0; q < 3 - Math.ceil(numOfEnters / 2.0); q++) {
                arr3 = "\n" + arr3;
            }

            lastSpace = 0;
            String arr4 = arr[4];
            numOfEnters = 0;
            j = 0;
            if (arr[4].length() > 45) {
                for (int i = 0; i < arr[4].length(); i++) {
                    if (arr[4].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 45) {
                        arr4 = arr4.substring(0, lastSpace) + "\n" + arr4.substring(lastSpace + 1);
                        j = i - lastSpace;
                        numOfEnters++;
                    }
                    j++;
                }
            }
            for (int q = 0; q < 3 - Math.ceil(numOfEnters / 2.0); q++) {
                arr4 = "\n" + arr4;
            }

            optionAJTextArea.setText(arr1);
            optionBJTextArea.setText(arr2);
            optionCJTextArea.setText(arr3);
            optionDJTextArea.setText(arr4);

            lastSpace = 0;
            String h = StaticMethods.findArray()[StaticMethods.findArray().length - 1];
            j = 0;
            if (StaticMethods.findArray()[StaticMethods.findArray().length - 1].length() > 60) {
                for (int i = 0; i < StaticMethods.findArray()[StaticMethods.findArray().length - 1].length(); i++) {
                    if (StaticMethods.findArray()[StaticMethods.findArray().length - 1].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 60) {
                        h = h.substring(0, lastSpace) + "\n" + h.substring(lastSpace + 1);
                        j = i - lastSpace;
                    }
                    j++;
                }
            }

            descriptionJTextArea.setText(h);
        
        }
    }//GEN-LAST:event_confirmJButtonActionPerformed

    private void optionBJTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionBJTextAreaMouseClicked
        option("B", 6, 1);
    }//GEN-LAST:event_optionBJTextAreaMouseClicked

    private void optionCJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCJPanelMouseClicked
        // TODO add your handling code here:
        option("C", 7, 2);
    }//GEN-LAST:event_optionCJPanelMouseClicked

    private void optionCJTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCJTextAreaMouseClicked
        // TODO add your handling code here:
        option("C", 7, 2);
    }//GEN-LAST:event_optionCJTextAreaMouseClicked

    private void optionDJTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDJTextAreaMouseClicked
        // TODO add your handling code here:
        option("D", 8, 3);
    }//GEN-LAST:event_optionDJTextAreaMouseClicked

    private void optionDJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDJPanelMouseClicked
        // TODO add your handling code here:
        option("D", 8, 3);
    }//GEN-LAST:event_optionDJPanelMouseClicked

    public void option(String letter, int description, int materials) {
        
        if (optionAJTextArea.getText().length() > 0 && !optionAJTextArea.getText().equalsIgnoreCase("\n\n\nLets Go!")) {
        
            boolean correct = StaticMethods.checkAnswer(letter);
            
            int lastSpace = 0;
            String arr1 = StaticMethods.findArray()[description];
            int j = 0;
            if (StaticMethods.findArray()[description].length() > 60) {
                for (int i = 0; i < StaticMethods.findArray()[description].length(); i++) {
                    if (StaticMethods.findArray()[description].charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 60) {
                        arr1 = arr1.substring(0, lastSpace) + "\n" + arr1.substring(lastSpace + 1);
                        j = i - lastSpace;
                    }
                    j++;
                }
            }

            if (Globals.phase.equalsIgnoreCase("Survey")) {

                if (correct) {

                    if (Globals.nasaFavour < Globals.FAVOUR_UP_CUTOFF) {
                        Globals.nasaFavour++;
                    }
                    StaticMethods.findPlanetMoon().numSurveyCorrect++;
                    
                    descriptionJTextArea.setText(arr1 + "\n" + "You gained a NASA Favour Point!\nYou have completed this task. Choose a new task.");
                    Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));
 
                    optionAJTextArea.setText("");
                    optionBJTextArea.setText("");
                    optionCJTextArea.setText("");
                    optionDJTextArea.setText("");
                    
                    int currentSurvey1 = 0;
                    for (int currentSurvey = 0; currentSurvey < StaticMethods.findPlanetMoon().surveyTasks.length; currentSurvey++) {
                        if (Globals.task.equalsIgnoreCase(StaticMethods.findPlanetMoon().surveyTasks[currentSurvey][0])) {
                            currentSurvey1 = currentSurvey;
                        }
                    }
                    
                    Globals.notes += "\n" + StaticMethods.findPlanetMoon().observations[currentSurvey1];

                } else {
                    Globals.nasaFavour--;
                    StaticMethods.findArray()[11] = StaticMethods.findArray()[11].substring(0, StaticMethods.findArray()[11].length() - 1);
                    optionAJTextArea.setText("");
                    optionBJTextArea.setText("");
                    optionCJTextArea.setText("");
                    optionDJTextArea.setText("");
                    
                    if (StaticMethods.findArray()[11].length() == 0) {
                        Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));
                        descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nYou have failed this task. Choose a new task.");
                        
                    } else {
                        descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nChoose your next task.");
                    }

                }
                
                if (Globals.currentComboBoxOptions.size() == 0) {
                        
                    Globals.phase = "Habitable";
                    for (int i = 0; i < StaticMethods.findPlanetMoon().habitableTasks.length; i++) {
                        Globals.currentComboBoxOptions.add(StaticMethods.findPlanetMoon().habitableTasks[i][0]);
                    }
                        
                }

            } else if (Globals.phase.equalsIgnoreCase("Habitable")) {

                if (!StaticMethods.findPlanetMoon().removeMaterials(materials)) {
                    
                    StaticMethods.findArray()[10] = StaticMethods.findArray()[10].substring(0, StaticMethods.findArray()[10].length() - 1);
                    
                    optionAJTextArea.setText("");
                    optionBJTextArea.setText("");
                    optionCJTextArea.setText("");
                    optionDJTextArea.setText("");
                    if (!correct){
                        Globals.nasaFavour--;
                        arr1 = "You do not have enough materials to build that!\nIt was a bad idea anyway.";
                        if (StaticMethods.findArray()[10].length() == 0) {
                            Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));
                            descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nYou have failed this task. Choose a new task.");

                        } else {
                            descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nChoose your next task.");
                        }
                        
                    } else {
                        descriptionJTextArea.setText("You do not have enough materials to build that!\nChoose your next task");
                        if (StaticMethods.findArray()[10].length() == 0) {
                            Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));
                        }
                    }
                } else {
                
                    if (correct) {
                        StaticMethods.findPlanetMoon().numHabitableCorrect++;
                        if (Globals.nasaFavour < Globals.FAVOUR_UP_CUTOFF) {
                            Globals.nasaFavour++;
                        }

                        descriptionJTextArea.setText(arr1 + "\n" + "You gained a NASA Favour Point!\nYou have completed this task. Choose a new task.");
                        Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));

                        optionAJTextArea.setText("");
                        optionBJTextArea.setText("");
                        optionCJTextArea.setText("");
                        optionDJTextArea.setText("");
                    } else {
                        Globals.nasaFavour--;
                        StaticMethods.findArray()[10] = StaticMethods.findArray()[10].substring(0, StaticMethods.findArray()[10].length() - 1);
                        optionAJTextArea.setText("");
                        optionBJTextArea.setText("");
                        optionCJTextArea.setText("");
                        optionDJTextArea.setText("");
                        if (StaticMethods.findArray()[10].length() == 0) {
                            Globals.currentComboBoxOptions.remove(Globals.currentComboBoxOptions.get(taskJComboBox.getSelectedIndex()));
                            descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nYou have failed this task. Choose a new task.");

                        } else {
                            descriptionJTextArea.setText(arr1 + "\nYou lost a NASA Favour Point!\nChoose your next task.");
                        }
                    }
                
                }
                
                if (Globals.currentComboBoxOptions.size() == 0) {
                        
                    if (StaticMethods.findPlanetMoon().canProgress()) {
                        String pop = "";
                        if (correct) {
                            pop = arr1 + "\nYou gained a NASA Favour Point!";
                        } else {
                            pop = arr1 + "\nYou lost a NASA Favour Point!";
                        }
                        
                        descriptionJTextArea.setText(pop + "\nGood job! You have completed your tasks on " + Globals.currentPlanetMoon + "!");
                        Globals.phase = "Survey";
                        Globals.currentLevel++;
                        Globals.inventory.get(0).incrementQuantity(100);

                        if (Globals.currentLevel > Globals.planetsAndMoons.length) {
                            String[] win = {"0"};
                            Globals.winning = 0;
                            new EndingScreen().runEndingScreen(win);
                            this.setVisible(false);
                        } else {
                            Globals.currentPlanetMoon = Globals.planetsAndMoons[Globals.currentLevel - 1].name;
                            for (int i = 0; i < StaticMethods.findPlanetMoon().surveyTasks.length; i++) {
                                Globals.currentComboBoxOptions.add(StaticMethods.findPlanetMoon().surveyTasks[i][0]);
                            }
                        }

                        levelNumJLabel.setText("LEVEL " + Globals.currentLevel + ": " + Globals.currentPlanetMoon.toUpperCase());
                        Globals.notes += "\n\n" + Globals.currentPlanetMoon;
                        
                        descriptionJTextArea.setText(descriptionJTextArea.getText() + "\nYou can now go to " + Globals.currentPlanetMoon + "!");
                        optionAJTextArea.setText("\n\n\nLets Go!");
                        optionBJTextArea.setText("\n\n\nLets Go!");
                        optionCJTextArea.setText("\n\n\nLets Go!");
                        optionDJTextArea.setText("\n\n\nLets Go!");
                        confirmJButton.setText("-----");
                        
                    } else {
                        
                        // they lose
                        this.setVisible(false);
                        String[] win = {"1"};
                        Globals.winning = 1;
                        new EndingScreen().runEndingScreen(win);
                        
                    }
                 
                }

            }

            numOfFavourPointsJLabel.setText("" + Globals.nasaFavour);
            if (Globals.nasaFavour < Globals.FAVOUR_CUTOFF) {
                String[] win = {"2"};
                Globals.winning = -1;
                new EndingScreen().runEndingScreen(win);
                this.setVisible(false);
            }

            String[] comboBoxOptions = new String[Globals.currentComboBoxOptions.size()];
            for (int i = 0; i < Globals.currentComboBoxOptions.size(); i++) {
                comboBoxOptions[i] = Globals.currentComboBoxOptions.get(i);
            }
            taskJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxOptions));
        
        } else if (optionAJTextArea.getText().equalsIgnoreCase("\n\n\nLets GO!")) {
            optionAJTextArea.setText("");
            optionBJTextArea.setText("");
            optionCJTextArea.setText("");
            optionDJTextArea.setText("");
            confirmJButton.setText("Confirm");
            String text = StaticMethods.findPlanetMoon().description;
            int lastSpace = 0;
            String arr1 = text;
            int numOfEnters = 0;
            int j = 0;
            if (text.length() > 60) {
                for (int i = 0; i < text.length(); i++) {
                    if (text.charAt(i) == ' ') {
                        lastSpace = i;
                    }
                    if (j == 60) {
                        arr1 = arr1.substring(0, lastSpace) + "\n" + arr1.substring(lastSpace + 1);
                        j = i - lastSpace;
                        numOfEnters++;
                    }
                    j++;
                }
            }
            descriptionJTextArea.setText(arr1 + " Choose a task.");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void runGame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buyJPanel;
    private javax.swing.JButton confirmJButton;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JButton exitGameJButton;
    private javax.swing.JButton exitGameJButton1;
    private javax.swing.JPanel inventoryJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel levelNumJLabel;
    private javax.swing.JPanel notesJPanel;
    private javax.swing.JLabel numOfFavourPointsJLabel;
    private javax.swing.JPanel optionAJPanel;
    private javax.swing.JTextArea optionAJTextArea;
    private javax.swing.JPanel optionBJPanel;
    private javax.swing.JTextArea optionBJTextArea;
    private javax.swing.JPanel optionCJPanel;
    private javax.swing.JTextArea optionCJTextArea;
    private javax.swing.JPanel optionDJPanel;
    private javax.swing.JTextArea optionDJTextArea;
    private javax.swing.JComboBox<String> taskJComboBox;
    // End of variables declaration//GEN-END:variables
}
