/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */


import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Sheena
 */
public class Globals {
    
    public static int winning = -1;
    public static int nasaFavour = 5;
    public static final int FAVOUR_CUTOFF = 0;
    public static final int FAVOUR_UP_CUTOFF = 10;
    public static String phase = "Habitable";
    public static String task = "Mission Planning";
    public static String currentPlanetMoon = "Earth";
    public static int currentLevel = 1;
    public static ArrayList<String> currentComboBoxOptions = new ArrayList<String>();
    public static String notes = "";
    
    public static ArrayList<InventoryObject> inventory = new ArrayList<InventoryObject>();
    
    public static HashMap<String, String> links = new HashMap<String, String>();
        
    // Earth Arrays
    public static String[] missionOne = new String[] {"Mission Planning", "Mission and technology development and proposal", "Design and complete technology needed for mission", "Assemble, test, and launch transportation needed for the mission", "All of the steps", "Your friend made you do all of the steps even though you didn’t want to. They prevented you from not having the transportation needed to go to space.", "Your friend made you do all of the steps even though you didn’t want to. They prevented you from spending billions of dollars creating technology that hasn’t yet been approved.", "Your friend made you do all of the steps even though you didn’t want to. They prevented you from creating unsafe transportation without planning in advance.", "You did all of the steps required and made an observation! ", "D", "1", "As a part of the necessary preparations that must be done before going to space, NASA needs you to do a set of tasks before you can complete your mission, which is to determine methods to make various celestial bodies habitable. Which of the following tasks do you want to complete?"};
    public static String[] missionTwo = new String[] {"Exercising", "30 minutes", "2 hours", "1 hour", "24 hours", "Your friend forced you to exercise for longer to prepare for the daily exercise in space and because exercise is important to prevent a loss of muscle mass in space.", "You are prepared to exercise in space and made an observation!", "Your friend forced you to exercise for longer to prepare for the daily exercise in space and because exercise is important to prevent a loss of muscle mass in space.", "Your friend reminded you of the importance of good sleep. Even though exercise is important to prepare for space, you still need to sleep.",  "B", "1", "NASA needs you to exercise daily on a treadmill and stationary bike to prepare you for the daily 2.5 hours of exercise done in space. How many hours will you exercise daily?"};
    public static String[] missionThree = new String[] {"Simulations", "Zero-gravity simulation: Experiencing what it’s like to have no gravity on Earth through a real-life simulation involving a harness and jumping without gravity", "Motion-based simulation: Experiencing what it’s like to travel in a space shuttle, practicing what to do with turbulence, and carrying out daily activities while traveling in space", "Spacesuit-based simulation: Practicing assembling different parts while wearing a spacesuit on Earth to experience what it’s like to assemble parts of a space ship in space", "All of them", "All simulations are necessary to be prepared for life in space, so your friend forces you to undergo the other simulators as well. They can also help prevent you from vomiting and possibly heart failure.", "All simulations are necessary to be prepared for life in space, so your friend forces you to undergo the other simulators as well. They can also help prevent you from vomiting and possibly heart failure,", "All simulations are necessary to be prepared for life in space, so your friend forces you to undergo the other simulators as well. They can also help prevent you from vomiting and possibly heart failure,", "You underwent the correct simulators to prepare for space and made an observation!",  "D", "1", "To prepare for your space adventures, you are required to undergo several simulations. Which of the following simulations do you want to do?"};
    public static String[] missionFour = new String[] {"Putting on Equipment", "A partial pressure suit, a parachute harness assembly, a parachute pack, and an oxygen tank", "A dress, high heels, and a designer bag from NASA", "A partial pressure suit, a carbon dioxide tank, and super cool socks", "Metal boots, a tuxedo, and a sunhat", "You made an observation and wore the correct equipment!", "Your friend stopped you from wearing the incorrect, although cool, equipment. They saved you from succumbing to the harsh cold, radiation, and low pressure in space.", "Your friend stopped you from wearing the incorrect, although cool, equipment. They saved you from succumbing to the harsh cold, radiation, and low pressure in space.", "Your friend stopped you from wearing the incorrect, although cool, equipment. They saved you from succumbing to the harsh cold, radiation, and low pressure in space.",  "A", "1", "In order to survive in space, NASA requires you to wear certain equipment. This is your last step before you are off to space! Which of the following equipment do you want to wear?"};
    public static InventoryObject specialInventory = new InventoryObject("Special", 0, "");
    public static InventoryObject[] specialInventoryArray = {specialInventory, specialInventory, specialInventory, specialInventory};
    

    // Moon ArrayLists
    public static String[] moonOne = new String[] {"Composition of Ground", "Observe the dirt", "Take a sample of the dirt with your bare hands", "Eat the dirt to determine the minerals present", "Lie down on the dirt", "You made an observation and determined the composition!", "Your friend stopped you from doing so and they think less of you.", "Your friend prevented you from getting food poisoning and gave you a space candy since they assumed you were hungry.", "You are now colder than usual but were not able to determine the composition of the ground.", "A", "blank", "11", "NASA needs you to determine the composition of the lunar regolith. How will you carry out this task?"};
    public static String[] moonTwo = new String[] {"Presence of Water", "Feel the soil to guess the moisture present", "Use a thermometer to find the temperature of the soil", "Determine water vapor ions present by using a mass spectrometer", "Guess how moist the water temperature is", "Your astronaut suit was too thick to feel the soil and determine its moisture content.", "The thermometer froze before you could determine the temperature of the soil.", "You were able to successfully determine the presence of water and made an observation!", "Your guess was not accurate.", "C", "blank", "11", "In order to determine the possibility of habitation on the moon, NASA would like you to figure out the presence of water on the satellite. How will you accomplish this?"};
    public static String[] moonThree = new String[] {"Temperature at Surface", "Take off your NASA spacesuit to determine how hot or cold it is", "Use a bolometer in order to determine the amount of IR radiation of the planet", "Feel the surface with your spacesuit still on", "Find an alien and ask them", "Your friend prevented you from taking off your suit and dying from a lack of oxygen.", "You successfully determined the surface temperature and made an observation!", "Your spacesuit was too thick to accurately determine the surface temperature.", "You could not find an alien successfully and are now tired.", "B", "blank", "11", "NASA would like you to determine the temperature at the surface of the Moon. How do you plan to do this task?"};
    public static String[] moonObservations = {"- The moon’s soil or the lunar regolith contains five different things: mineral fragments and agglutinates produced from minor meteorite impacts, minute crystalline and breccia rock fragments, and impact lunar glasses resulting from the shock of meteoroid impacts\nshock of meteoroid impacts\n" +
"- The chemical composition of the lunar surface is generally composed of 50% silicon dioxide, 15% aluminum oxide, 10% calcium oxide, 10% magnesium oxide, 5% titanium oxide and 5-15% iron", "- The north and south poles of the moon consist of over 600 billion kilograms of water ice", "- Surface temperatures near the equator during the day can reach around 250℉, approx. 120℃ or 400K and surface temperatures can reach around -208℉, approx. -130℃ or 140K, although the north and south poles can be colder"};
    
    // type of thing, next 4 are options, next 4 are sentences describing what happens, correct answer
    public static String[] moon1 = new String[] {"Make shelter", "Make a wooden hut (requires 10 wood)", "Make a concrete house (requires 5 concrete)", "Build a metal base made with aluminum (requires 10 aluminum sheets)", "Lie down and cry", "Your wooden shelter floats away because of the lack of gravity on the moon.", "Your concrete house unfortunately cracked and broke down", "Your house withstood the strength of the extreme conditions of the moon!", "Your friend recommends you see a therapist to address your many issues.", "C", "11", "In order to survive the flying debris and weather conditions of the planet, you need to create a shelter for yourself and your crewmates on the moon. How will you create a shelter?" };
    public static String[] moon2 = new String[] {"Build infrastructure 1", "Make a landing station (requires 10 aluminum sheets)", "Gossip with your friend", "Read a book", "Build a regolith snowman", "You successfully built a landing station for other spacecraft!", "You gossip with your friend and accidentally hurt a co-worker’s feelings.", "You read the latest sci-fi novel, but caught the ire of your supervisor.", "Your coworkers see you fail horribly on making a regolith snowman.", "A", "11", "You would like to build infrastructure that ensures you can safely land on the Moon. What will you do?"};
    public static String[] moon3 = new String[] {"Build infrastructure 2", "Chat with your friend", "Build a farm (requires 5 food pods)", "Play moonball", "Build a regolith snowman", "Your friend talk about how disgusting space food is.", "You successfully built a farm that can sustain a human colony!", "You play the game moonball with your coworkers. Your team unfortunately lost.", "Your coworkers see you fail horribly on making a regolith snowman.", "B", "11", "You require infrastructure that can sustain a human colony. How will you accomplish this?" };
    public static String[] moon4 = new String[] {"Build infrastructure 3", "Play video games", "Talk with your friends.", "Build a water purification center (requires 10 aluminum sheets)", "Build a regolith snowman", "You lock yourself in your room and play SpaceBlasters. You feel incredibly guilty for not doing any work.", "You and your friends talk about yesterday’s moonball match, which made you feel discouraged.", "You draft the plans for a state-of-the-art water purification center that will unfreeze lunar ice and turn it into potable water!", "Your coworkers see you fail horribly on making a regolith snowman.", "C", "11", "In order to survive on the Moon, you and your crewmates require safe drinking water. How will you ensure this happens?" };

    
    public static InventoryObject nothing = new InventoryObject("", 0, "no u");
    public static String placeholder_image = "";
    public static InventoryObject[] moon_1 = {new InventoryObject("Wooden Plank", 10, placeholder_image), new InventoryObject("Concrete Block", 5, placeholder_image), new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing};
    public static InventoryObject[] moon_2 = {new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing, nothing, nothing};
    public static InventoryObject[] moon_3 = {nothing, new InventoryObject("Food Pod", 5, placeholder_image), nothing, nothing};
    public static InventoryObject[] moon_4 = {nothing, nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing};
    public static InventoryObject[][] moonMaterials = {moon_1, moon_2, moon_3, moon_4};
    
    // MARS
    public static String[] marsOne = new String[] {"Composition of Ground", "Look at a speck of soil under a magnifying glass", "Research predetermined data on the composition of the ground on Mars", "Feel the consistency of the soil", "Plant a tree and observe how it behaves", "You could not find any soil to observe.", "You successfully determined the composition and made an observation!", "You could not find any soil and are now sad.", "You could not find any soil that supports a tree’s growth.", "B", "blank", "11", "NASA requests for you to determine the composition of the ground on Mars. What will you do to complete this assignment?" };
    public static String[] marsTwo = new String[] {"Composition of Atmosphere", "Take off your breathing mask and breathe in Mars’ atmosphere", "Do nothing", "Jump around to determine how thick the atmosphere is", "Use a device to detect the traces of gasses on Mars", "Your friend prevented you from dying from a lack of oxygen.", "You weren’t successful in determining the composition of the atmosphere.", "You had fun but didn’t determine the composition.", "You successfully determined the composition of the atmosphere and made an observation!",  "D", "blank", "11", "To get a grasp on the celestial history of Mars and use that knowledge to consider the possibility of humans living on the planet, NASA requires you to figure out the composition of the planet’s atmosphere. What steps will you take to succeed in doing this?"};
    public static String[] marsThree = new String[] {"Presence of Water", "Use predetermined data from NASA", "Guess the water molecules based on how moist the atmosphere feels", "Plant a tree and see if it survives", "Touch the ground and determine how wet it is", "You made an observation and determined the presence of water!", "Your spacesuit was too thick to determine how the atmosphere feels.", "Your food pod in your inventory is too small to plant a tree.", "You could not successfully feel how wet the ground is because your spacesuit is too thick.",  "A", "blank", "11", "You would like to determine whether there is water on Mars. How will you figure this out?"};
    public static String[] marsFour = new String[] {"Temperature at Surface", "Use E. Coli to detect the surface temperature", "Ask your educated space friend who knows everything about Mars", "Let out some of your oxygen gas to see how it behaves", "Play a card game with your friend", "The E. Coli bacteria died very quickly due to Mars’ atmosphere and could never detect the temperature in the first place.", "Your friend correctly told you Mars’ surface temperature and you made an observation!", "Your friend prevented you from opening your oxygen tank as you would not have enough oxygen during your time in space.", "You found out you love playing card games where the cards float around but did not determine Mars’ surface temperature.", "B", "blank", "11", "You realize that to understand the planet better, you need to know the temperature at the surface of Mars. How will you determine the surface temperature of Mars?"};
    public static String[] marsObservations = {"- The surface of Mars is covered with a thick layer of fine oxidised iron dust, which gives the planet its red colour. The crust underneath the dust is made of volcanic basalt rock, which is rich in minerals like sodium, potassium, and magnesium.", "- Mars' atmosphere is much thinner compared to Earth's. It's 95% carbon dioxide.", "- There are trace amounts of water present within the soil as ice, and there is ice present in the polar ice caps.", "- The surface temperature of Mars ranges from 68oF (20oC) to 307oF (153oC)."};
    
    public static String[] mars1 = new String[] {"Make shelter", "Make a concrete house (requires 5 concrete)", "Make a wooden hut (requires 10 wood)",  "Read a 500 page novel on the positive effects of green tea", "Build a metal base made with aluminum (requires 10 aluminum sheets)", "Your concrete house unfortunately cracked and broke down", "Your wooden shelter floats away because of the lack of gravity on the moon.", "You end up falling asleep out of boredom and waste 6 hours of your research time.", "Your house withstood the strength of the extreme conditions of Mars!", "D", "11",  "In order to survive the flying debris and weather conditions of the planet, you need to create a shelter for yourself and your crewmates on Mars. How will you create a shelter?"};
    public static String[] mars2 = new String[] {"Build infrastructure 1", "Create a house of cards.", "Make a landing station (requires 10 aluminum sheets).", "Play tic-tac-toe with your friend.", "Have a regolith ball fight with your crewmates.",  "You have fun building a house of cards but the planet’s weather conditions knock it over.", "You successfully built a landing station for other spacecraft!", "Your supervisor catches you and your friend slacking off and gives you both a time-out.", "You horribly lose to the opposing team and become the laughing stock of your crew. ", "B", "11", "You would like to build infrastructure that ensures you can safely land on Mars. How will you accomplish this?"};
    public static String[] mars3 = new String[] {"Build infrastructure 2", "Build a farm (requires 5 food pods)", "Challenge your friend to a sprinting race.", "Build a regolith snowangel", "Play a card game with your crewmates.", "You successfully built a farm that can sustain a human colony!", "You attempt to sprint in your heavy spacesuit and trip over your feet.", "You try to cheat during the card game, but get caught and lose the trust of your crewmates.", "You have fun building a regolith snow angel but it gets ruined from the windy weather on Mars.", "A", "11", "You require infrastructure that can sustain a human colony on Mars. How will you accomplish this?"};
    public static String[] mars4 = new String[] {"Build infrastructure 3", "Eat a family pack of Mars chocolate bars.", "Play charades with your crewmates.", "Play video games.", "Build a water purification center (requires 10 aluminum sheets).", "You ate too much chocolate and start to feel sick.", "The spacesuit makes it extremely hard for your crewmates to understand you.",  "You lock yourself in your room and play SpaceBlasters. You feel incredibly guilty for not doing any work.", "You draft the plans for a state-of-the-art water purification center that will unfreeze lunar ice and turn it into potable water!", "D", "11", "In order to survive on Mars, you and your crewmates require safe drinking water. How will you ensure this happens?"};
    public static String[] mars5 = new String[] {"Obtain more oxygen", "Take off your helmet and breathe in the air on Mars.", "Do nothing and hope that there will be enough oxygen to sustain your crewmates and yourself.",  "Use the cyanobacteria you brought with you to convert the carbon dioxide in Mars’ atmosphere into oxygen (requires 10 cyanobacteria).", "Use nitrogen to fill up your oxygen tank instead.", "Your friend stopped you from taking off your space helmet and dying from the lack of oxygen.", "You and your crewmates’ oxygen tanks start to run out and you regret doing nothing about it.", "You managed to obtain more oxygen from using the cyanobacteria and made an observation!.", "You realize that filling up your oxygen tank with nitrogen was useless and now you require more oxygen than before.", "C", "11", "In order to survive on Mars, you need to have more oxygen in your oxygen tank. How will you accomplish this?"};
    public static InventoryObject[] mars_1 = {new InventoryObject("Concrete Block", 5, placeholder_image), new InventoryObject("Wooden Plank", 10, placeholder_image), nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image)};
    public static InventoryObject[] mars_2 = {nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing, nothing};
    public static InventoryObject[] mars_3 = {new InventoryObject("Food Pod", 5, placeholder_image), nothing, nothing, nothing};
    public static InventoryObject[] mars_4 = {nothing, nothing, nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image)};
    public static InventoryObject[] mars_5 = {nothing, nothing, new InventoryObject("Cyanobacteria", 10, placeholder_image)};
    public static InventoryObject[][] marsMaterials = {mars_1, mars_2, mars_3, mars_4, mars_5};
    
    // TITAN
    public static String[] titanOne = new String[] {"Composition of Ground", "Find dirt on the moon to observe", "Find a bacteria on the planet and ask them about the composition of the ground", "Determine the composition of the ground based on the planet’s bulk density of 1.88 g/cm^3", "Guess the composition to be the same as Earth’s ground composition", "You searched for hours but could not find any dirt on the planet. Instead, you found only hydrocarbon particles, and were not able to determine the composition based on the particles you found.", "You unfortunately did not find any bacteria that could talk and help you in your quest to find the composition of Titan’s ground.", "You successfully determined the composition of Titan’s ground and made an observation!", "You were incorrect in your guessing and could not determine the composition of Titan’s ground.", "C", "blank", "11", "NASA needs you to determine the composition of the mighty Titan moon. How will you find out the composition?"};
public static String[] titanTwo = new String[] {"Composition of Atmosphere", "Guess that the composition is the same as Earth’s moon because both Titan and Earth’s moon are moons", "Use NASA’s online database to determine Titan’s atmospheric composition", "Use Wikipedia to determine Titan’s atmospheric composition", "Take of your oxygen mask and breathe in the atmosphere", "Just because both are moons, they don’t have the same atmosphere. You were incorrect in your guess.", "You successfully determined the composition of the atmosphere and made an observation!", "Wikipedia is a source that can be changed by anyone, so you got the incorrect atmosphere composition of Titan and weren’t successful.", "Your friend prevented you from dying from a lack of oxygen.",  "B", "blank", "11", "NASA needs you to determine Titan’s atmospheric composition. How will you succeed in doing this?"};
public static String[] titanThree = new String[] {"Presence of Water", "Use the Cassini spacecraft's gravity measurements to determine the presence of Titan’s underground water", "Guess the water molecules based on how moist the atmosphere feels", "Exercise for 2.5 hours and observe how much you sweat", "Find a lake and swim in it", "You made an observation and determined the presence of water!", "Your spacesuit was too thick to determine how the atmosphere feels.", "Though you got in your daily exercise, you were not able to determine the presence of water on Titan.", "You found a lake but your friend prevented you from swimming in it and encountering unknown bacteria.",  "A", "blank", "11", "Your next task is to discover the presence of water on Titan. What will be your method in doing this?"};
public static String[] titanFour = new String[] {"Temperature", "Watch a movie in space", "Try finding an alien on Titan and asking them", "Heat a pizza in a convection pizza and observe if the pizza gets warm", "Ask your friend who knows about Titan’s temperature measurements made by the Composite Infrared Spectrometer", "You discovered that your new hobby is watching movies in space but did not determine Titan’s temperature.", "Your friend prevented you from going on the search and forced you to play a floating board game with them instead.", "The convection oven warmed the pizza, despite the temperature of Titan, and you were unsuccessful in determining the temperature of Titan.", "You determined the temperature of Titan and made an observation!", "D", "blank", "11", "You realize that there is one more fact that will help you determine how to live on Titan; the temperature. How will you figure out the temperature of Titan?"};
public static String[] titanObservations = {"- Titan’s ground is composed mainly of rock-hard ice. The ground’s surface also has various organic molecules.", "- Titan's atmosphere is made mainly of Nitrogen, which is very similar to Earth’s atmosphere. Its surface pressure, however, is around 50% higher than that of Earth’s.", "- Titan has many lakes, seas, and rivers of hydrocarbons like ethane and methane. Some of the largest seas on this moon are hundreds of miles wide and even hundreds of feet deep. Beneath the rock-hard ice itself, there is also an ocean primarily of water.", "- The surface temperature of Titan ranges from -291.2oF (-179.6oC) to 38.3oF (3.5oC), which is the temperature of the winter pole of Titan."};

public static String[] titan1 = new String[] {"Make shelter", "Make a concrete house (requires 5 concrete)", "Make a wooden hut (requires 10 wood)",  "Build a metal base made with aluminum (requires 10 aluminum sheets)", "Skateboard around the satellite.", "Your concrete house unfortunately cracked and broke down", "Your wooden shelter floats away because of the lack of gravity on the moon.", "You tripped over the titan regolith and scraped your suit.", "Your house withstood the strength of the extreme conditions of Mars!", "C", "In order to survive the flying debris and weather conditions of the planet, you need to create a shelter for yourself and your crewmates on Titan. How will you create a shelter?"};
public static String[] titan2 = new String[] {"Build infrastructure 1", "Write a poem on the beauty of Titan", "Binge watch a TV show", "Read an article on the current affairs of your favourite celebrity",  "Make a landing station (requires 10 aluminum sheets)", "You write a beautiful haiku on Titan’s atmospheric conditions but fail to create a safe landing station for other spacecraft", "You become too emotionally attached to the characters and as a result, feel terrible when you finish the show", "You are caught up on the private life of your celebrity crush, but NASA is disappointed in you for failing to create new infrastructure", "You successfully built a landing station for other spacecraft.", "D", "You would like to build infrastructure that ensures you can safely land on Mars. How will you accomplish this?"};
public static String[] titan3 = new String[] {"Build infrastructure 2", "Complain to your friend about how you want to return home", "Challenge your friend to an arm wrestle", "Collaborate with your fellow astronauts to dedicate a space in your space shuttle to a greenhouse", "Challenge your friend to who can name more NASA astronauts", "Your friend is sad that you are not enjoying your space mission and encourages you to push through.", "You won the arm wrestle but are now especially hungry because you were not successful in creating a greenhouse.", "You successfully built a mini greenhouse with your food pods!", "You lost the challenge to your friend and NASA is disappointed in you because you also could not make a greenhouse.", "C", "You require a dedicated area to growing food on Titan. How will you complete this challenge?"};
public static String[] titan4 = new String[] {"Build infrastructure 3", "Eat space icecream", "Have a long chat with your astronaut friends on how to create a chocolate milk fountain", "Build a water purification center that extracts water from deep within titan and filters it (requires 10 alluminum sheets)", "Be lazy and do nothing.", "You loved the space icecream so much that it is now your favourite food. However, now you are very thirsty.", "You successfully obtained clean drinking water from Titan!", "You obtained some much needed rest, but still need to figue out how to obtain safe drinking water.", "C", "In order to survive on Titan, you and your crewmates require safe drinking water as all of your water ran out during your seven year travel. How will you do this task?"};
public static String[] titan5 = new String[] {"Obtain more oxygen", "Try breathing without your oxygen tank as the atmosphere of Earth and Titan both have nitrogen", "Extract oxygen given by the plant from a food pod (requires 1 foodpod)", "Plant a tree to provide you oxygen", "Play floating hopscotch", "Your friend prevented you from dying from a lack of oxygen.", "You successfully increased the amount of oxygen in your oxygen tank.", "Titan has a rocky and icy ground so it trees cannot grow. You were not able to successfully obtain more oxygen.", "You had a lot of fun but did not get more oxygen.", "B", "In order to survive on Titan, you need to have more oxygen in your oxygen tank. Which of the following tasks will you do?"};
public static String[] titan6 = new String[] {"Repair the Sewage System", "Hold in any urges you get", "Float while playing the violin",  "Team up with your crewmates to upgrade the waste collector system (requires 5 aluminum sheets)", "Play freeze-tag with your crewmates", "You hold in your body waste until your stomach hurts and end up fainting", "You serenade your crewmates with a few pieces but are in pain due to not being able to relieve yourself", "You and your crewmates successfully repaired the sewage system!", "You had a lot of fun but were not able to fix the sewage system", "C", "In order to survive on Titan, you need to relieve yourself and dispose of your wastes. Which of the following tasks will you do?"};

public static  InventoryObject[] titan_1 = {new InventoryObject("Concrete Block", 5, placeholder_image), new InventoryObject("Wooden Plank", 5, placeholder_image), new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing};
public static  InventoryObject[] titan_2 = {nothing, nothing, nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image)};
public static  InventoryObject[] titan_3 = {nothing, nothing, nothing, nothing};
public static  InventoryObject[] titan_4 = {nothing, nothing, new InventoryObject("Aluminum Sheet", 10, placeholder_image), nothing};
public static  InventoryObject[] titan_5 = {nothing, new InventoryObject("Food Pod", 1, placeholder_image), nothing, nothing};
public static  InventoryObject[] titan_6 = {nothing, nothing, new InventoryObject("Aluminum Sheet", 5, placeholder_image), nothing};
public static InventoryObject[][] titanMaterials = {titan_1, titan_2, titan_3, titan_4, titan_5, titan_6};

    
    // 2d array, one dimension is the inventory, other row is quantity
    // for these ones the last option is to not do anything
    public static PlanetMoon[] planetsAndMoons = new PlanetMoon[] {new PlanetMoon("Earth", 1, "You must do a series of activities before you can successfully visit space. Planning a space mission can sometimes take years, and training usually lasts for about 2 years, so be prepared!", new String[][] {}, new String[][] {missionOne, missionTwo, missionThree, missionFour}, new InventoryObject[][] {specialInventoryArray, specialInventoryArray, specialInventoryArray, specialInventoryArray}, moonObservations),
    new PlanetMoon("The Moon", 2, "After 3 days of space travel, you have arrived Earth’s very own moon! It is around 27% the size of Earth, and is the only place that humans have set foot on so far in space. It is your goal to determine the characteristics of the moon and make it habitable using items in your inventory.", new String[][] {moonOne, moonTwo, moonThree}, new String[][] {moon1, moon2, moon3, moon4}, moonMaterials, moonObservations), 
    new PlanetMoon("Mars", 3, "After about 9 months of travel from the Moon, you've arrived at Mars, the 4th planet from the sun. Billions of years ago, the atmosphere was likely Earth-like with oceans of liquid water, but now many features of Mars make it uninhabitable. It's your job to observe the traits of Mars and perfom daily tasks on the planet.", new String[][] {marsOne, marsTwo, marsThree, marsFour}, new String[][] {mars1, mars2, mars3, mars4, mars5}, marsMaterials, marsObservations), 
    new PlanetMoon("Titan", 4, "7 years later, you have arrived at Titan, the largest of Saturn's moons. In the solar system, Titan is the only moon that has a substantial atmosphere and the second largest moon overall. There is a possibility of life on Titan, and it your job to observe the traits of the moon and find a way to live on it.", new String[][] {titanOne, titanTwo, titanThree, titanFour}, new String[][] {titan1, titan2, titan3, titan4, titan5, titan6}, titanMaterials, titanObservations)};
    
}
